name: dispatched build-docker-image

on:
  repository_dispatch:
    types:
      - dispatch-build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: checkout frontier-squid
      uses: actions/checkout@v2

    - name: make date tag
      id: mkdatetag
      run: echo "::set-output name=dtag::$(date +%Y%m%d-%H%M)"

    - name: fake build
      run: echo dispatched ${{ steps.mkdatetag.outputs.dtag }}

